// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     writer.avsc
 */
package writer

import (
	"io"

	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

func writeArrayBar(r []Bar, w io.Writer) error {
	err := vm.WriteLong(int64(len(r)), w)
	if err != nil || len(r) == 0 {
		return err
	}
	for _, e := range r {
		err = writeBar(e, w)
		if err != nil {
			return err
		}
	}
	return vm.WriteLong(0, w)
}

type ArrayBarWrapper struct {
	Target *[]Bar
}

func (_ ArrayBarWrapper) SetBoolean(v bool)                { panic("Unsupported operation") }
func (_ ArrayBarWrapper) SetInt(v int32)                   { panic("Unsupported operation") }
func (_ ArrayBarWrapper) SetLong(v int64)                  { panic("Unsupported operation") }
func (_ ArrayBarWrapper) SetFloat(v float32)               { panic("Unsupported operation") }
func (_ ArrayBarWrapper) SetDouble(v float64)              { panic("Unsupported operation") }
func (_ ArrayBarWrapper) SetBytes(v []byte)                { panic("Unsupported operation") }
func (_ ArrayBarWrapper) SetString(v string)               { panic("Unsupported operation") }
func (_ ArrayBarWrapper) SetUnionElem(v int64)             { panic("Unsupported operation") }
func (_ ArrayBarWrapper) Get(i int) types.Field            { panic("Unsupported operation") }
func (_ ArrayBarWrapper) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ ArrayBarWrapper) Finalize()                        {}
func (_ ArrayBarWrapper) SetDefault(i int)                 { panic("Unsupported operation") }
func (r ArrayBarWrapper) HintSize(s int) {
	if len(*r.Target) == 0 {
		*r.Target = make([]Bar, 0, s)
	}
}
func (r ArrayBarWrapper) NullField(i int) {
	panic("Unsupported operation")
}

func (r ArrayBarWrapper) AppendArray() types.Field {
	var v Bar
	v = NewBar()

	*r.Target = append(*r.Target, v)
	return &types.Record{Target: &(*r.Target)[len(*r.Target)-1]}
}
